version: '1.0'

stages:
  - build
  - test
  - deploy

steps:
  environment_prep:
    stage: build
    title: Prepare Build Environment
    image: codefreshio/git-image:latest
    commands:
      - cf_export FEATURE_NAME=$(echo "$CF_BRANCH" | sed -n -E -e "s/^(feature|release)\/(.*)/\2/p")
      - cf_export BUILD_TAG=$(echo "${CF_BRANCH_TAG_NORMALIZED}" | tr '[:upper:]' '[:lower:]')

  pipeline_prep:
    stage: build
    title: Check Feature Build
    image: codefreshio/git-image:latest
    commands:
      - cf_export BUILD_TAG=$(echo "${FEATURE_NAME}" | tr '[:upper:]' '[:lower:]')
    when:
      condition:
        all:
          isFeatureBranch: "Boolean('${{FEATURE_NAME}}') == true"

  build_image:
    stage: build
    title: Build Synapse Docker Image
    type: build
    working_directory: ${{main_clone}}
    dockerfile: docker/Dockerfile
    image_name: aloha-matrix
    tag: ${{CF_SHORT_REVISION}}

  push_image:
    stage: deploy
    title: Push GCR Image
    type: push
    candidate: ${{build_image}}
    image_name: aloha-matrix
    tags:
      - ${{CF_SHORT_REVISION}}
      - ${{BUILD_TAG}}
    registry: gcr

  push_chart:
    stage: deploy
    title: Push Helm Chart
    image: codefresh/cfstep-helm:2.12.3
    environment:
      - ACTION=push
      - CHART_REF=devops/k8s/chart/aloha-matrix
      - CMD_PS=--force

  deploy_chart:
    stage: deploy
    title: Deploy to Kubernetes Cluster
    image: codefresh/cfstep-helm:2.12.3
    environment:
      - ACTION=install
      - CHART_REF=aloha-matrix
      - RELEASE_NAME=${{BUILD_TAG}}-matrix
      - VALUE_image_tag=${{CF_SHORT_REVISION}}
      - VALUE_image_pullPolicy=Always
    when:
      condition:
        all:
          isFeatureBranch: "Boolean('${{FEATURE_NAME}}') == true"
